### ISSUE TITLE
Confusion about PLL algorithms

### ISSUE THREAD

**Issue by nastaran-kianersi** [mhshammakhi/SDR_GPU#2]
PLL_Parallel/ForwardBackward directory is (as the name suggests) about two algorithms, but the README file is only about forward-backward. The .exe is FB, while the .lib is the parallel algorithm. Do we need both algorithms or only one? Do we need to provide the lib for forward-backward?

**Comment by mhshammakhi** [comment]
Thank you for being so considerate.
I should check but I thought both of them (FB and parallel algorithm) existed in the lib file. The correct version should contain the FB version in the '.lib' file.  I am eager to add the 'parallel algorithm' folder beside the 'FB' version.

**Comment by nastaran-kianersi** [comment]
@mhshammakhi Thank you, I got it. I will fix this. I got something wrong, though. I thought PLL_Parallel/ForwardBackward was the name of a folder while it actually indicated that ForwardBackward is a sub-folder of PLL_Parallel. I'm also not sure if this is the best place for such discussions, so you might wanna consider enabling the Discussions part in the repository.
